Repository hackforla/tdm-calculator, pull requests merged in 2025-04, with the labels that each got.

#2320 2111 style input controls
  client/src/components/Projects/ColumnHeaderPopups/MultiSelectText.jsx
  client/src/components/Projects/ColumnHeaderPopups/TextPopup.jsx
  client/src/components/UI/RadioButton.jsx
  client/src/components/UI/UniversalSelect.jsx
  client/src/styles/App.scss
Labels: role: front-end

#2340 1897 Add padding to dropdowns to match the style guide
  client/src/components/UI/UniversalSelect.jsx
Labels: role: front-end

#2355 2315 Fix project filters persisting across logins
  client/src/components/Authorization/Logout.jsx
  client/src/components/Projects/ProjectsPage.jsx
  client/src/helpers/Constants.js
Labels: role: front-end, ready for dev lead

#2377 center select relevant projects table
  client/src/components/Feedback/ProjectList.jsx
Labels: ready for dev lead

#2408 fix(login): apply secondary style to 'Continue Without Saving' button
  client/src/components/Authorization/Login.jsx
Labels: role: front-end, ready for dev lead - front end

#2366 Make Reset Filters button visible on small-width screens
  client/src/components/Projects/ProjectsPage.jsx
Labels: role: front-end, ready for dev lead - front end

#2416 Fix: Display trash icons by default
  client/src/components/Faq/CategoryInputContainer.jsx
  client/src/components/Faq/FaqButtonContainer.jsx
Labels: role: front-end, ready for DEV Lead-PD

#2323 2282 fix client tests
  client/babel.config.cjs
  client/jest.config.cjs
  client/package-lock.json
  client/package.json
  client/src/components/Layout/NavBar.test.jsx
  client/src/components/ProjectWizard/WizardPages/Level0Page.test.jsx
  client/src/components/Projects/ProjectTableRow.test.jsx
  server/__tests__/email.test.js
  server/db/flyway-config.js
Labels: role: front-end, ready for dev lead

#2473 2428 Change Name to Project Name
  client/src/components/Feedback/FeedbackPage.jsx
  client/src/components/Feedback/ProjectList.jsx
  client/src/components/Projects/ProjectsPage.jsx
  client/src/components/SubmitSnapshot/SubmitSnapshotPage.jsx
Labels: role: front-end, ready for DEV Lead-PD

#2368 update RuleInput so that error messages are aligned with input boxes
  client/src/components/ProjectWizard/RuleInput/ProjectLevelRuleInput.jsx
  client/src/components/ProjectWizard/RuleInput/RuleInput.jsx
  client/src/components/ProjectWizard/RuleInput/RuleInputList.jsx
  client/src/components/ProjectWizard/RuleInput/RuleInputPanels.jsx
  client/src/components/ProjectWizard/TdmCalculationWizard.jsx
  client/src/components/ProjectWizard/WizardPages/ProjectDescriptions.jsx
  client/src/components/ProjectWizard/WizardPages/ProjectSpecifications.jsx
Labels: role: front-end, ready for DEV Lead-PD

#2468 2375 add tabs to projects page
  client/src/components/Projects/ColumnHeaderPopups/StatusPopup.jsx
  client/src/components/Projects/MultiProjectToolbarMenu.jsx
  client/src/components/Projects/ProjectTableRow.jsx
  client/src/components/Projects/ProjectsPage.jsx
Labels: role: front-end, ready for DEV Lead-PD

#2485 Update Styling for the FAQ Answers
  client/src/components/Faq/Answer.jsx
  client/src/components/UI/Quill.jsx
  client/src/styles/AdminQuill.scss
Labels: role: front-end, ready for dev lead
